spring.application.name=APSRest
spring.datasource.url=jdbc:oracle:thin:@localhost:10.16.134.23
spring.datasource.username=c##manutencao
spring.datasource.password=manutencao
spring.jpa.properties.hibernate.dialect=org.hibertane.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true